name: SkyTrials
version: '${version}'
main: com.github.lukesky19.skytrials.SkyTrials
api-version: '1.21'
authors: [ lukeskywlker19 ]
depend:
    - SkyLib
    - WorldGuard
softdepend:
  - Multiverse-Core
load: POSTWORLD

permissions:
  skytrials.command.skytrials:
    description: The base command permission.
    default: op
  skytrials.command.skytrials.join:
    description: The permission to join a trial.
    default: op
  skytrials.command.skytrials.start:
    description: The permission to start a trial.
    default: op
  skytrials.command.skytrials.leave:
    description: The permission to leave a trial.
    default: op
  skytrials.command.skytrials.help:
    description: The permission to view the help message.
    default: op
  skytrials.command.skytrials.reload:
    description: The permission to reload the plugin.
    default: op
  skytrials.command.skytrials.cooldown:
    description: The permission to view a cooldown
    default: op